services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "exec gunicorn 'app.main:app' --workers 4 --bind 0.0.0.0:8050 --access-logfile /var/log/app/backend_access.log --error-logfile /var/log/app/backend_error.log"
    volumes:
      - ./backend/reports:/app/reports
      - ./backend/uploads:/app/uploads
      - logs:/var/log/app
    environment:
      - MAX_IMAGE_PIXELS=25000000 # e.g., 5000x5000
      - BATCH_TIMEOUT_S=300
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    volumes:
      - logs:/var/log/app
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  reports:
  uploads:
  logs:
