services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - cie-lab-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - cie-lab-network

networks:
  cie-lab-network:
