version: '3.8'

services:
  metallobox:
    build: .
    container_name: metallobox-app
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=host.docker.internal:0
      - QT_X11_NO_MITSHM=1
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
