services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./backend/reports:/app/reports
      - ./backend/uploads:/app/uploads
    environment:
      - MAX_IMAGE_PIXELS=25000000 # e.g., 5000x5000
      - BATCH_TIMEOUT_S=300
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  reports:
  uploads:
